sudo: required
language: node_js

dist: precise

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang

node_js:
  - '4'
env:
  global:
  - secure: FvhNfXjIwmwsoe8hVljAxk/tCJ+YZOr+2hRtc6PZRnV4D2gtjsY7iX2oSE88GyLof2jMAW4MTc6odk8+U1Aqxke+Cc6Nna+GiR1tt1RinlcJ51jA1RVD48onBW7s1dcNSCJXmyEknSFPxp3PRIdS4P5uA04el1XoMOMXcoCebuxkthez8i3VF0M+4IieR9383DNWQTI9f3slmTxnfci807yIzTI0hn0njYR8mqJTPtXGnfmZSdlZPS1WMQlv8suEjIMTqR2ikYwcwwTx1r0d3oz8u4Kml3mWfLrY7BNl8dvNGpJERkB2ozHoWC0HDu68wegmXxRBE/f8bZRZ124G/P2JCCBACP9aY2fE5LoYB6qi0HXMLAYk25vu1XaHcVj8h9u/n2nkm6T7nsND/SqE1b4NUBlA7Psf885kd4LP+yed7Y9rz8054Fcn5jyrXZV7i4adRW+qsFVRbytcYm2D3xkMN+CHVAqlU6OEmJ7qLdthoYYeG/bPInbMq21HOwcUJ8lp6cGOjRXeAQzZ2G1Xjtn4pxzqrmE+WL8bfxe1ALgI0zsEVq03FohKWHQuwzG8okKOEMpBlOzsOmg3FAlWO1O+UHjBhyFVW5NrCKashasTfybqhUXDDdFt2GrduOMXoBwvm/pHQeMrJxwAg3fn8uVaPNp5K+dAly2bVCscLfQ=
  - secure: uJlvtoPtXDsjAoGuBxcQ7uF3VOomkAw4K5h8wpqXKaQnvpF0SHSHcFFLZFdd90nlECX0NLEt9hE4z3Zum4SR7u6oHWvGSO6edJI+IS4DfqZWe+pYWe6czn2ObV141XH3d2A65Mz4959+69s4SFuOwx6EearLoqkOXtn8fjQLDkNU/hd3FHjKBZliNEFfmjyA8LnQyZxsaPVMK6NcSUc3H3rODWuamlhJX9s024aUtNzmqqWit/G5u7BcL3eAuAXvrF6zJAoI088O/rCxI9FjJ5zuBgkHlM/pJWyxxE8Ow88TcQ1iTuOsr2PSZHWqO+O4AngM20mrzBnA0f6kZrvKH59n63pLGtsj0OMMWy724l6715oDjHd3Qnk0X+wJInMqtpGq2j2AhMGzZPd0zLwNZBfVOgcgAd+X9oFqRUGlYkY3HbiXEMO/dTCnNFhpCjA4bv5F5GtUBwaKUM3SlRiTUWa5fxpa/52oCtcHGxLt7hLLlgKVLcz8TfmUVWdRZ8xf9MP0aa5Nnuq6Cs4bYcd7E0HAYpgYNCSkwAyj/WojJTysgKCN0PDQvFqsawsfyEgFrwKEwrLm/qMdmfsWcUJxrocMJ953J/sK8An8EiNb/Z/qxVhqOM4LI5j837rIUUW87aFNaknUL5508slJezj1nkytbe/5p9FeZ9+J57gK+rk=

os:
  - linux

osx_image: xcode8.2

env:
  matrix:
    - TABLEAU_SDK_VERSION=10-2-0

before_install:
  - ./scripts/install-sdk.sh
  - npm install node-gyp -g
  - npm install node-pre-gyp
  - npm install aws-sdk
  - PUBLISH_BINARY=false
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;
  - platform=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
install:
  - npm install --build-from-source
before_script:
  - echo "Publishing native platform Binary Package? ->" $PUBLISH_BINARY
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish || true; fi;
  - node-pre-gyp clean
  - node-gyp clean
script:
  - INSTALL_RESULT=0
  - if [[ $PUBLISH_BINARY == true ]]; then INSTALL_RESULT=$(npm install --fallback-to-build=false > /dev/null)$? || true; fi;
  - if [[ $INSTALL_RESULT != 0 ]]; then echo "returned $INSTALL_RESULT";node-pre-gyp unpublish;false; fi
  - node-pre-gyp clean
after_success:
  - node-pre-gyp info