sudo: required
language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang

node_js:
  - '4'

os:
  - linux
  - osx

osx_image: xcode8.2

env:
  matrix:
    - TABLEAU_SDK_VERSION=10-2-0

before_install:
  - ./scripts/install-sdk.sh
  - npm install node-gyp -g
  - npm install node-pre-gyp
  - npm install aws-sdk
  - platform=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
install:
  - npm install --build-from-source
before_script:
  - echo "Publishing native platform Binary Package? ->" $PUBLISH_BINARY
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish || true; fi;
  - node-pre-gyp clean
  - node-gyp clean
script:
  - INSTALL_RESULT=0
  - if [[ $PUBLISH_BINARY == true ]]; then INSTALL_RESULT=$(npm install --fallback-to-build=false > /dev/null)$? || true; fi;
  - if [[ $INSTALL_RESULT != 0 ]]; then echo "returned $INSTALL_RESULT";node-pre-gyp unpublish;false; fi
  - node-pre-gyp clean
after_success:
  - node-pre-gyp info