sudo: required
language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang

node_js:
  - '4.4'

os:
  - linux
  - osx

matrix:
  allow_failures:
    # waiting: https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540
    - os: linux

before_install:
  - ./scripts/install-sdk.sh

install:
  - npm install

script:
  - export MALLOC_CHECK_=1 # @todo: Fix double free / corruption error and remove this line.
  - npm test
